services:
    statemachine.listener.history:
        class: StateMachineBundle\Listener\HistoryListener
        arguments:
#            TODO make object manager dyanmically depends on config
#            - @service_container
            - @doctrine.orm.entity_manager
            - @security.token_storage

    statemachine.factory:
        class: StateMachineBundle\StateMachine\StateMachineFactory
        arguments:
            - ~

    statemachine.subscriber.doctrine_loader:
        class: StateMachineBundle\Subscriber\StateMachineLoaderSubscriber
        arguments:
            - @statemachine.factory
        tags:
            - { name: doctrine.event_subscriber }

    statemachine.subscriber.persistent:
        class: StateMachineBundle\Subscriber\PersistentSubscriber
        tags:
            - { name: kernel.event_subscriber }
        arguments:
            - @doctrine.orm.entity_manager
#TODO make object manager dyanmically depends on config
