services:
    statemachine.factory:
        class: StateMachineBundle\StateMachine\StateMachineFactory
        arguments:
            - @statemachine.history_manager
            - ~

    statemachine.subscriber.doctrine_loader:
        class: StateMachineBundle\Subscriber\StateMachineLoaderSubscriber
        arguments:
            - @statemachine.factory
            - @security.token_storage
        tags:
            - { name: doctrine.event_subscriber }

    statemachine.history_manager:
        class: StateMachineBundle\History\PersistentHistoryManager
        arguments:
            - @doctrine
            - @security.token_storage

    statemachine.twig.state_machine:
        class: StateMachineBundle\Twig\StateMachineExtension
        tags:
            - { name: twig.extension }

    test_callback:
        class: StateMachineBundle\Tests\Listeners\MockListener
