services:
    statemachine.listener.history:
        class: StateMachine\Listener\HistoryListener

    statemachine.factory:
        class: StateMachineBundle\StateMachine\StateMachineFactory
        arguments:
            - @event_dispatcher
            - ~
            - ~

    statemachine.subscriber.doctrine_loader:
        class: StateMachineBundle\Subscriber\StateMachineLoaderSubscriber
        arguments:
            - @statemachine.factory
        tags:
            - { name: doctrine.event_subscriber }
