version: 2
jobs:
   build:
     docker:
       - image: circleci/php:7.1-cli
     steps:
       - run: echo 'date.timezone = Europe/Berlin' | sudo tee --append /usr/local/etc/php/php.ini
       - run: echo 'memory_limit=1024M' | sudo tee --append /usr/local/etc/php/php.ini
       - checkout
       - run:
           name: Composer install
           command: |
             sudo composer self-update
             composer install -n --prefer-dist
       - run:
           name: Check code style
           command: |
             MASTER_MERGE_BASE=($(git merge-base origin/master HEAD))
             COMMIT_RANGE="$MASTER_MERGE_BASE..HEAD"
             IFS=$'\n'; COMMIT_SCA_FILES=($(git diff --name-only --diff-filter=ACMRTUXB "${COMMIT_RANGE}")); unset IFS
             ./vendor/bin/php-cs-fixer fix --config=.php_cs.dist -v --dry-run --using-cache=no --path-mode=intersection "${COMMIT_SCA_FILES[@]}"
       - run:
           name: Run unit tests
           command: ./vendor/bin/phpunit --configuration=src/phpunit.xml.dist
