version: 2
jobs:
   build:
     docker:
       - image: circleci/php:5.6-fpm
     steps:
       - run: echo 'date.timezone = Europe/Berlin' | sudo tee --append /usr/local/etc/php/php.ini
       - run: echo 'memory_limit=1024M' | sudo tee --append /usr/local/etc/php/php.ini
       - checkout
       - run:
           name: Composer install
           command: |
             sudo composer self-update
             composer install -n --prefer-dist
       - run:
           name: Run unit tests
           command: ./vendor/bin/phpunit --configuration=src/phpunit.xml.dist
