StateMachineBundle\Entity\Transition:
    type: entity
    table: statemachine_transitions
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        fromState:
            type: string
            length: 255
            column: from_state
        toState:
            type: string
            length: 255
            column: to_state
        createdAt:
            column: created_at
            type: datetime
            nullable: false
        identifier:
            type: integer
        objectClass:
            type: string
            length: 255
            column: object_class
        preTransitions:
            type: json_array
            column: pre_transitions
            nullable: true
        postTransitions:
            type: json_array
            column: post_transitions
            nullable: true
        guards:
            type: json_array
            nullable: true
        failedCallback:
            type: string
            length: 255
            column: failed_callback
            nullable: true
        passed:
            type: boolean
            column: is_passed
        messages:
            type: json_array
            nullable: true
    lifecycleCallbacks: {  }
